### GKSL equation in Kossakowski form for the augmented Bloch vector 

According to the theorem proven by Kossakowski (Kossakowski, 1973) Markovian master equation could be rewritten for a two-level system $\rho \in M(2)$ as follows:

$
   \mathcal{K} = -i[H,\rho] + \frac{1}{2} \sum_{i,j}^3 C_{ij} \{[f_i, \rho f_j] + [f_i\rho, f_j]\}, 
$
where

$
\text{(i)} \quad \quad 
           f_i f_j = \frac{1}{4}\delta_{ij}I  +\frac{i}{2} \sum_{k=1}^3 \epsilon_{ijk} f_k \\ \text{which means:} \notag \\ \quad
    \operatorname{Tr}(f_i f_j)=\frac{1}{2}\delta_{ij}, \quad \operatorname{Tr}(f_i) = 0 \notag 
$


and we can choose basis operators $f_i$ as halfs of Pauli matrices 
$\{ \sigma_x, \sigma_y, \sigma_z \}$:

$
    f_1 = \sigma_x/2  = 
    \begin{pmatrix}
        0 & 1 \\ 1 & 0
    \end{pmatrix} / 2 \\
    f_2 = \sigma_y/2  = \begin{pmatrix}
        0 & i \\ -i & 0
    \end{pmatrix} / 2\\
    f_3 = \sigma_z/2 = \begin{pmatrix}
        1 & 0 \\ 0 & -1
    \end{pmatrix} / 2
$

$
     \text{(ii)} \quad \quad \quad 
     H = \sum_1^3 h_i f_i, \quad h_i \in \mathbb{R}
$

which means we can use Hamiltonian of the form:

$
H = \begin{pmatrix} 
h_3   & h_1 + i h_2          \\
h_1 - i h_2 & -h_3
\end{pmatrix} / 2 \\
 = \begin{pmatrix} 
h_z   & h_x + i h_y          \\
h_x - i h_y & -h_z
\end{pmatrix} / 2 
$

$
     \text{(iii)} \quad \{C_{ij}\} = \begin{pmatrix} 
\gamma - 2\gamma_1    & - i a_3            &  i a_2 \\
i a_3                 & \gamma - 2\gamma_2 & -i a_1 \\
-i a_2                & i a_1              & \gamma - 2\gamma_3 
\end{pmatrix} 
=  \begin{pmatrix} 
\kappa_1   & - i a_3    &  i a_2 \\
i a_3       & \kappa_2   & -i a_1 \\
-i a_2      & i a_1      & \kappa_3 
\end{pmatrix}
$

$C =  \begin{pmatrix}
c_{11} & c_{12} & c_{13} \\
c_{21} & c_{22} & c_{23} \\
c_{31} & c_{32} & c_{33}
\end{pmatrix}$

$
    \text{(iv)} \quad \quad \quad \quad \gamma_1, \gamma_2, \gamma_3 \geq 0
$

If $\gamma = 0$ the evolution is just unitary, and in case $\gamma >0 $ <br>
in order for the evolution to be completely positive it is nessesary and sufficient that <br>
(denoting $\kappa_i = \gamma - 2 \gamma_i$):

$
    \kappa_1 + \kappa_2 + \kappa_3 \geq 0 \\
\kappa_1 \kappa_2  + \kappa_3 \kappa_1  + \kappa_1 \kappa_2  \geq a_1^2 + a_2^2 + a_3^2 \\
   \kappa_1 \kappa_2 \kappa_3 \geq  \kappa_1 a_1^2 + \kappa_2 a_2^2 + \kappa_3 a_3^2 
$

Standard GKSL in Bloch vector form:

$
\frac{d\mathbf{r}}{dt} = \mathbf{\omega} \times \mathbf{r} - \Lambda \mathbf{r} + \mathbf{b}
$

where $\omega$ = $\{ h_1, h_2, h_3 \}$

$\mathbf{\omega} \times \mathbf{r} = \Omega \cdot \mathbf{r}  
= \begin{pmatrix}
0 & -h_z & h_y \\
h_z & 0 & -h_x \\
-h_y & h_x & 0
\end{pmatrix} \cdot \mathbf{r} $ 

Drift vector: $\mathbf{b} = 2 \sum_{i,j=1}^3 \operatorname{Im} C_{ij} \epsilon_{kij}$ with $\epsilon_{kij}$ - Levi-Civita symbol

$\mathbf{b} = 2 \operatorname{Im}  \begin{pmatrix} c_{23}-c_{32} \\ c_{31} - c_{13} \\ c_{12} - c_{21} \end{pmatrix} 
= 2 \operatorname{Im} \begin{pmatrix} -2i a_1 \\ -2i a_2 \\ -2i a_3 \end{pmatrix} = 2 \begin{pmatrix} -2 a_1 \\ -2 a_2 \\ -2 a_3 \end{pmatrix}$

Damping matrix:

$\Lambda_{kl} = 2 \sum_{i,j=1}^3 C_{ij} (\delta_{jk}\delta_{jl} - \frac{1}{2}\delta_{ij}\delta_{kl})$

$
\Lambda = 2 \begin{pmatrix}
c_{11} - \operatorname{Tr}(C) & c_{12} & c_{13} \\
c_{12} & c_{22} - \operatorname{Tr}(C) & c_{23} \\
c_{13} & c_{23} & c_{33} - \operatorname{Tr}(C)
\end{pmatrix}
$

$
\Lambda = 2 \left( C - \operatorname{Tr}(C) \, I \right)
$

#### GKSL for augmented Bloch vector

$\frac{d\mathbf{\tilde{r}}}{dt} = \tilde{A_c} \mathbf{\tilde{r}}$


$\tilde{A_c} = 
\begin{pmatrix}
-\Lambda + \Omega & \mathbf{b} \\
\mathbf{0}^T &  0
\end{pmatrix}
$

In [1]:
using DynamicPolynomials
using LinearAlgebra

In [2]:
@polyvar κ[1:3]; κ₁,κ₂,κ₃ = κ[1],κ[2],κ[3]
@polyvar a[1:3]; a₁,a₂,a₃ = a[1],a[2],a[3]

Cˢʸᵐᵇ = [  κ₁     -im*a₃     im*a₂
           im*a₃   κ₂       -im*a₁
          -im*a₂   im*a₁     κ₃     ] ;

Λ = 2*(Cˢʸᵐᵇ - tr(Cˢʸᵐᵇ)*I)

@polyvar h[1:3]; h₁,h₂,h₃ = h[1],h[2],h[3]

Hˢʸᵐᵇ = [ h₃          h₁+im*h₂
          h₁-im*h₂   -h₃           ] / 2

Ω = [  0   -h₃     h₂
       h₃   0     -h₁
      -h₂   h₁     0    ]  

b = -4 * [a₁ a₂ a₃]'

3×1 Matrix{Term{true, Int64}}:
 -4a₁
 -4a₂
 -4a₃

In [52]:
Acˢʸᵐᵇ = [-Λ+Ω       b
          zeros(3)'  0]

4×4 Matrix{Polynomial{true, ComplexF64}}:
 (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃                                        …  (-4.0+0.0im)a₁
 (2.0+0.0im)κ₁ + (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃ + (0.0-2.0im)a₃ + h₃      (-4.0+0.0im)a₂
 (2.0+0.0im)κ₁ + (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃ + (0.0+2.0im)a₂ + -h₂     (-4.0+0.0im)a₃
 0.0+0.0im                                                               0.0+0.0im

In [50]:
using HDF5

filename = "../MODELS/DMD_b4_LTI_trn4_2024-Sep-15_at_00-06.h5"

γ = [ "0.079477",  "0.25133", "0.79477", "2.5133", "7.9477", "25.133",  "79.477", "251.33"]

γᵢ = γ[3]

function read_LSID_Ac(γᵢ)

    h5open(filename, "r") do file
        # Navigate to the dataset within the group
        Ac = read(file["gamma_"*γᵢ*"/Ac"])
        
        # Now you can use the dataset as needed
        return(Ac)
    end
end 

Acˢⁱᵈ  = read_LSID_Ac(γᵢ)

4×4 Matrix{Float64}:
 -1.09155e-8   -25.1327        0.000161443   2.89442e-5
 25.1963        -0.795828     -0.000818289  -7.03521e-5
 -0.0366884     -0.00621641   -0.798674      0.79106
 -2.95082e-13   -4.98227e-13  -3.37554e-13  -2.0922e-14

Consider transfer function $G(s)$ should be the same for the all possible realisations ($A_c, C, \mathbf{x}(0)$) of the system.

Then transfer function for the some analytically assumed structure of matrices $\tilde{A_c}$ and $\tilde{C}$ could be equated to the transfer function calculated for the matrices  $\hat{A_c}^{(SID)}$ and $\hat{C}^{(SID)}$ estimated by ERA or DMD *system identification algorithm* algorithm:
$\begin{align}
   \tilde{C}(sI - \tilde{A_c})^{-1} \mathbf{x}(0) = \hat{C}^{(SID)}\left(sI - \hat{A_c}^{(SID)}\right)^{-1} \mathbf{x}(0)
\end{align}$ 

as we use augmented Bloch vectors as *internal state variable* then matrox $C$ is known 
$\tilde{C} = \hat{C}^{(SID)}$

$
\begin{pmatrix} \rho_{00} \\
\rho_{01} \\
\rho_{10} \\
\rho_{11} 
\end{pmatrix} 
= \frac{1}{2}
\begin{pmatrix} 
0 & 0 & 1 & 1 \\
1 & -i & 0 & 0 \\
1 & i & 0 & 0 \\
0 & 0 & -1 & 1 \\
\end{pmatrix}
\begin{pmatrix} 
\mathbf{b} \\
1
\end{pmatrix} $

Thus we can remole $C$ from consideration, and as we exactly know the initial states $\mathbf{x}(0)$ we can also remove it

$\begin{align}
   (sI - \tilde{A_c})^{-1} = \left(sI - \hat{A_c}^{(SID)}\right)^{-1}
\end{align}$ 

If matrices $sI - \tilde{A_c}$ and $sI - \hat{A_c}^{(SID)}$ are actually invertable, then:

$\begin{align}
   sI - \tilde{A_c} = sI - \hat{A_c}^{(SID)}
\end{align}$ 

Which means matrices  $\tilde{A_c}$ and $\hat{A_c}^{(SID)}$ are actually elementwise equal:

$\begin{align}
   \tilde{A_c} = \hat{A_c}^{(SID)}
\end{align}$ 

In [67]:
Ac=copy(Acˢⁱᵈ)

Ac[abs.(Ac) .< 1e-6] .= 0.0

D = Ac[1:3,1:4] - Acˢʸᵐᵇ[1:3,1:4]

3×4 Matrix{Polynomial{true, ComplexF64}}:
 (-2.0-0.0im)κ₂ + (-2.0-0.0im)κ₃                                                              …  (4.0-0.0im)a₁ + (2.89442e-5+0.0im)
 (-2.0-0.0im)κ₁ + (-2.0-0.0im)κ₂ + (-2.0-0.0im)κ₃ + (-0.0+2.0im)a₃ + -h₃ + (25.1963+0.0im)       (4.0-0.0im)a₂ + (-7.03521e-5+0.0im)
 (-2.0-0.0im)κ₁ + (-2.0-0.0im)κ₂ + (-2.0-0.0im)κ₃ + (-0.0-2.0im)a₂ + h₂ + (-0.0366884+0.0im)     (4.0-0.0im)a₃ + (0.79106+0.0im)

In [54]:
using Symbolics

In [55]:
function poly_to_symbolic(poly, var_map)
    expr = zero(Num)

    # Get the coefficients and monomials from the polynomial
    coeffs = MultivariatePolynomials.coefficients(poly)
    monoms = MultivariatePolynomials.monomials(poly)

    # Loop over the coefficients and corresponding monomials
    for (coeff, monomial) in zip(coeffs, monoms)
        monomial_expr = one(Num)
        
        if isa(monomial, Number)
            # If the monomial is a constant, use it directly
            monomial_expr = Num(monomial)
        else
            # Otherwise, convert monomials to symbolic form
            vars_in_monomial = MultivariatePolynomials.variables(monomial)
            exponents_in_monomial = MultivariatePolynomials.exponents(monomial)

            # Build the symbolic monomial expression
            for (var, exponent) in zip(vars_in_monomial, exponents_in_monomial)
                # Ensure that the variable is in var_map
                if haskey(var_map, var)
                    # Replace the polynomial variable with the corresponding symbolic variable
                    monomial_expr *= var_map[var]^exponent
                else
                    error("Variable $var not found in variable map.")
                end
            end
        end
        
        # Add the coefficient * monomial_expr to the overall expression
        expr += real(coeff) * monomial_expr
    end
    return expr
end

poly_to_symbolic (generic function with 1 method)

In [57]:
@variables ks1, ks2, ks3, as1, as2, as3, hs1, hs2, hs3

poly_var_to_sym_var = Dict(
κ₁ => ks1,
κ₂ => ks2,
κ₃ => ks3,
a₁ => as1,
a₂ => as2,
a₃ => as3,
h₁ => hs1,
h₂ => hs2,
h₃ => hs3
#κ[1] => k1, #κ[2] => k2, #κ[3] => k3,
#a[1] => a1, #a[2] => a2, #a[3] => a3,
#h[1] => h1, #h[2] => h2, #h[3] => h3
)

Dict{PolyVar{true}, Num} with 9 entries:
  a₃ => as3
  h₁ => hs1
  a₂ => as2
  h₃ => hs3
  κ₁ => ks1
  κ₂ => ks2
  κ₃ => ks3
  a₁ => as1
  h₂ => hs2

In [70]:
constr1 = κ₁ + κ₂ + κ₃ 
constr2 = κ₁*κ₂ + κ₃*κ₁ + κ₂*κ₃ - a₁^2 - a₂^2 - a₃^2
constr3 = κ₁*κ₂*κ₃ - κ₁*a₁^2 - κ₂*a₂^2 - κ₃*a₃^2

constraints = [ h₃, κ₁, κ₂, κ₃, constr1, constr2, constr3] 

constraints_sym = [poly_to_symbolic(c, poly_var_to_sym_var) for c in constraints]

constraints_sym[1:5]

5-element Vector{Num}:
             hs3
             ks1
             ks2
             ks3
 ks1 + ks2 + ks3

In [68]:
#using Symbolics

equations = []

for i in 1:size(D, 1)-1
    for j in 1:size(D, 2)
        # Convert to symbolic expression
        expr = poly_to_symbolic(D[i, j], poly_var_to_sym_var)
        
        # Use iszero to check if the expression is zero
        if !iszero(expr)
            push!(equations, expr ~ 0)
        end
    end
end

equations

8-element Vector{Any}:
 -2.0ks2 - 2.0ks3 ~ 0
 hs3 - 25.132740902749152 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
 0.00016144287336491446 - hs2 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
 2.894417436333362e-5 + 4.0as1 ~ 0
 25.19633229486415 - hs3 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
 -0.7958275809831139 - 2.0ks1 - 2.0ks3 ~ 0
 hs1 - 0.0008182885461700876 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
 4.0as2 - 7.035206592688032e-5 ~ 0

In [69]:
# Solve the system symbolically
sol = Symbolics.solve_for(equations, [ks1, ks2, ks3, as1, as2, as3, hs1, hs2, hs3])

SingularException: SingularException(6)

In [65]:
equations_constraints = equations

for expr in constraints_sym[1:5]
    if !iszero(expr)
        push!(equations_constraints, expr > 0)
    end
end

equations_constraints

13-element Vector{Any}:
                      -1.0915482301539226e-8 - 2.0ks2 - 2.0ks3 ~ 0
                      hs3 - 25.132740902749152 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
                      0.00016144287336491446 - hs2 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
                      2.894417436333362e-5 + 4.0as1 ~ 0
                      25.19633229486415 - hs3 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
                      -0.7958275809831139 - 2.0ks1 - 2.0ks3 ~ 0
                      hs1 - 0.0008182885461700876 - 2.0ks1 - 2.0ks2 - 2.0ks3 ~ 0
                      4.0as2 - 7.035206592688032e-5 ~ 0
               hs3 > 0
               ks1 > 0
               ks2 > 0
               ks3 > 0
 (ks1 + ks2 + ks3) > 0

In [66]:
# Solve the system symbolically
sol = Symbolics.solve_for(equations_constraints, [ks1, ks2, ks3, as1, as2, as3, hs1, hs2, hs3])

AssertionError: AssertionError: islinear