### GKSL equation in Kossakowski form for the augmented Bloch vector 

According to the theorem proven by Kossakowski (Kossakowski, 1973) Markovian master equation could be rewritten for a two-level system $\rho \in M(2)$ as follows:

$
   \mathcal{K} = -i[H,\rho] + \frac{1}{2} \sum_{i,j}^3 C_{ij} \{[f_i, \rho f_j] + [f_i\rho, f_j]\}, 
$
where

$
\text{(i)} \quad \quad 
           f_i f_j = \frac{1}{4}\delta_{ij}I  +\frac{i}{2} \sum_{k=1}^3 \epsilon_{ijk} f_k \\ \text{which means:} \notag \\ \quad
    \operatorname{Tr}(f_i f_j)=\frac{1}{2}\delta_{ij}, \quad \operatorname{Tr}(f_i) = 0 \notag 
$


and we can choose basis operators $f_i$ as halfs of Pauli matrices 
$\{ \sigma_x, \sigma_y, \sigma_z \}$:

$
    f_1 = \sigma_x/2  = 
    \begin{pmatrix}
        0 & 1 \\ 1 & 0
    \end{pmatrix} / 2 \\
    f_2 = \sigma_y/2  = \begin{pmatrix}
        0 & i \\ -i & 0
    \end{pmatrix} / 2\\
    f_3 = \sigma_z/2 = \begin{pmatrix}
        1 & 0 \\ 0 & -1
    \end{pmatrix} / 2
$

$
     \text{(ii)} \quad \quad \quad 
     H = \sum_1^3 h_i f_i, \quad h_i \in \mathbb{R}
$

which means we can use Hamiltonian of the form:

$
H = \begin{pmatrix} 
h_3   & h_1 + i h_2          \\
h_1 - i h_2 & -h_3
\end{pmatrix} / 2 \\
 = \begin{pmatrix} 
h_z   & h_x + i h_y          \\
h_x - i h_y & -h_z
\end{pmatrix} / 2 
$

$
     \text{(iii)} \quad \{C_{ij}\} = \begin{pmatrix} 
\gamma - 2\gamma_1    & - i a_3            &  i a_2 \\
i a_3                 & \gamma - 2\gamma_2 & -i a_1 \\
-i a_2                & i a_1              & \gamma - 2\gamma_3 
\end{pmatrix} 
=  \begin{pmatrix} 
\kappa_1   & - i a_3    &  i a_2 \\
i a_3       & \kappa_2   & -i a_1 \\
-i a_2      & i a_1      & \kappa_3 
\end{pmatrix}
$

$C =  \begin{pmatrix}
c_{11} & c_{12} & c_{13} \\
c_{21} & c_{22} & c_{23} \\
c_{31} & c_{32} & c_{33}
\end{pmatrix}$

$
    \text{(iv)} \quad \quad \quad \quad \gamma_1, \gamma_2, \gamma_3 \geq 0
$

If $\gamma = 0$ the evolution is just unitary, and in case $\gamma >0 $ <br>
in order for the evolution to be completely positive it is nessesary and sufficient that <br>
(denoting $\kappa_i = \gamma - 2 \gamma_i$):

$
    \kappa_1 + \kappa_2 + \kappa_3 \geq 0 \\
\kappa_1 \kappa_2  + \kappa_3 \kappa_1  + \kappa_1 \kappa_2  \geq a_1^2 + a_2^2 + a_3^2 \\
   \kappa_1 \kappa_2 \kappa_3 \geq  \kappa_1 a_1^2 + \kappa_2 a_2^2 + \kappa_3 a_3^2 
$

Standard GKSL in Bloch vector form:

$
\frac{d\mathbf{r}}{dt} = \mathbf{\omega} \times \mathbf{r} - \Lambda \mathbf{r} + \mathbf{b}
$

where $\omega$ = $\{ h_1, h_2, h_3 \}$

$\mathbf{\omega} \times \mathbf{r} = \Omega \cdot \mathbf{r}  
= \begin{pmatrix}
0 & -h_z & h_y \\
h_z & 0 & -h_x \\
-h_y & h_x & 0
\end{pmatrix} \cdot \mathbf{r} $ 

Drift vector: $\mathbf{b} = 2 \sum_{i,j=1}^3 C_{ij} \epsilon_{kij}$ with $\epsilon_{kij}$ - Levi-Civita symbol

$\mathbf{b} = 2 \begin{pmatrix} c_{23}-c_{32} \\ c_{31} - c_{13} \\ c_{12} - c_{21} \end{pmatrix} 
= 2 \begin{pmatrix} -2i a_1 \\ -2i a_2 \\ -2i a_1 \end{pmatrix}$

Damping matrix:

$\Lambda_{kl} = 2 \sum_{i,j=1}^3 C_{ij} (\delta_{jk}\delta_{jl} - \frac{1}{2}\delta_{ij}\delta_{kl})$

$
\Lambda = 2 \begin{pmatrix}
c_{11} - \operatorname{Tr}(C) & c_{12} & c_{13} \\
c_{12} & c_{22} - \operatorname{Tr}(C) & c_{23} \\
c_{13} & c_{23} & c_{33} - \operatorname{Tr}(C)
\end{pmatrix}
$

$
\Lambda = 2 \left( C - \operatorname{Tr}(C) \, I \right)
$

#### GKSL for augmented Bloch vector

$\frac{d\mathbf{\tilde{r}}}{dt} = \tilde{M} \mathbf{\tilde{r}}$


$\tilde{M} = 
\begin{pmatrix}
-\Lambda + \Omega & \mathbf{b} \\
\mathbf{0}^T &  0
\end{pmatrix}
$

In [4]:
using DynamicPolynomials
using LinearAlgebra

In [9]:
@polyvar κ[1:3]; κ₁,κ₂,κ₃ = κ[1],κ[2],κ[3]
@polyvar a[1:3]; a₁,a₂,a₃ = a[1],a[2],a[3]

Cˢʸᵐᵇ = [  κ₁     -im*a₃     im*a₂
           im*a₃   κ₂       -im*a₁
          -im*a₂   im*a₁     κ₃     ] ;

Λ = 2*(Cˢʸᵐᵇ - tr(Cˢʸᵐᵇ)*I)

@polyvar h[1:3]; h₁,h₂,h₃ = h[1],h[2],h[3]

Hˢʸᵐᵇ = [ h₃          h₁+im*h₂
          h₁-im*h₂   -h₃           ] / 2

Ω = [  0   -h₃     h₂
       h₃   0     -h₁
      -h₂   h₁     0    ]  

b = -4im * [a₁ a₂ a₃]'

3×1 Matrix{Term{true, Complex{Int64}}}:
 (0 - 4im)a₁
 (0 - 4im)a₂
 (0 - 4im)a₃

In [17]:
M = [-Λ+Ω       b
     zeros(3)'  0]

4×4 Matrix{Polynomial{true, ComplexF64}}:
 (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃                                        …  (0.0-4.0im)a₁
 (2.0+0.0im)κ₁ + (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃ + (0.0-2.0im)a₃ + h₃      (0.0-4.0im)a₂
 (2.0+0.0im)κ₁ + (2.0+0.0im)κ₂ + (2.0+0.0im)κ₃ + (0.0+2.0im)a₂ + -h₂     (0.0-4.0im)a₃
 0.0+0.0im                                                               0.0+0.0im

In [41]:
using HDF5

filename = "../MODELS/DMD_b4_LTI_trn4_2024-Sep-15_at_00-06.h5"

γ = [ "0.079477",  "0.25133", "0.79477", "2.5133", "7.9477", "25.133",  "79.477", "251.33"]

γᵢ = γ[3]

function read_LSID_Ac(γᵢ)

    h5open(filename, "r") do file
        # Navigate to the dataset within the group
        Ac = read(file["gamma_"*γᵢ*"/Ac"])
        
        # Now you can use the dataset as needed
        return(Ac)
    end
end 

A_c = read_LSID_Ac(γᵢ)

4×4 Matrix{Float64}:
 -1.09155e-8   -25.1327        0.000161443   2.89442e-5
 25.1963        -0.795828     -0.000818289  -7.03521e-5
 -0.0366884     -0.00621641   -0.798674      0.79106
 -2.95082e-13   -4.98227e-13  -3.37554e-13  -2.0922e-14

In [43]:
M[1,1]

(2.0 + 0.0im)κ₂ + (2.0 + 0.0im)κ₃

In [26]:
include("../LiPoSID.jl")

Main.LiPoSID

In [28]:
obj = LiPoSID.frobenius_norm2(A_c - M)

(32.0 + 0.0im)κ₁² + (56.0 + 0.0im)κ₁κ₂ + (56.0 + 0.0im)κ₁κ₃ + (32.0 + 0.0im)κ₂² + (56.0 + 0.0im)κ₂κ₃ + (32.0 + 0.0im)κ₃² + (24.0 + 0.0im)a₁² + (24.0 + 0.0im)a₂² + (24.0 + 0.0im)a₃² + (2.0 + 0.0im)h₁² + (2.0 + 0.0im)h₂² + (2.0 + 0.0im)h₃² + (1.9680425651667506 + 0.0im)κ₁ + (0.962498439267985 + 0.0im)κ₂ + (0.960950824423794 + 0.0im)κ₃ + (0.0005447456638448244 + 0.0im)h₁ + (-0.01077512970133796 + 0.0im)h₂ + (-100.56575436516539 + 0.0im)h₃ + (1264.3736419260417 + 0.0im)

In [29]:
obj = sum(real(coef) * mon for (coef, mon) in zip(coefficients(obj), monomials(obj)))

32.0κ₁² + 56.0κ₁κ₂ + 56.0κ₁κ₃ + 32.0κ₂² + 56.0κ₂κ₃ + 32.0κ₃² + 24.0a₁² + 24.0a₂² + 24.0a₃² + 2.0h₁² + 2.0h₂² + 2.0h₃² + 1.9680425651667506κ₁ + 0.962498439267985κ₂ + 0.960950824423794κ₃ + 0.0005447456638448244h₁ - 0.01077512970133796h₂ - 100.56575436516539h₃ + 1264.3736419260417

In [30]:
using TSSOS

function min_cs_tssos(p, constrs)

    coeffs = coefficients(p)
    reg_coef = 0

    pop =[p+reg_coef*sum(variables(p).^2), constrs...] ./ maximum(abs.(coeffs))

    d = maxdegree(p)
    
    # Initial optimization step
    opt, sol, data = cs_tssos_first(pop, variables(pop), d; solution=true, QUIET=true)
    ref_sol, flag = TSSOS.refine_sol(opt, sol, data; QUIET=true)
    prev_opt, prev_sol, prev_data = opt, sol, data 

    # Check if the solution needs further refinement
    if flag != 0
        while ~isnothing(sol) && flag != 0
            prev_opt, prev_sol, prev_data = opt, sol, data
            opt, sol, data = cs_tssos_higher!(data; solution=true, QUIET=true) 
        end
        ref_sol, flag = TSSOS.refine_sol(prev_opt, prev_sol, prev_data; QUIET=true)
    end

    solution = variables(p) => ref_sol

    if flag == 0 
        status_name = "GLOBAL"
    else
        status_name = "LOCAL/FAIL"
    end

    return solution, status_name

end

min_cs_tssos (generic function with 1 method)

In [32]:
constr1 = κ₁ + κ₂ + κ₃ 
constr2 = κ₁*κ₂ + κ₃*κ₁ + κ₂*κ₃ - - a₁^2 - a₂^2 - a₃^2
constr3 = κ₁*κ₂*κ₃ - κ₁*a₁^2 - κ₂*a₂^2 - κ₃*a₃^2

constraints = [ h₃, κ₁, κ₂, κ₃, constr1, constr2, constr3] 

7-element Vector{Polynomial{true, Int64}}:
 h₃
 κ₁
 κ₂
 κ₃
 κ₁ + κ₂ + κ₃
 κ₁κ₂ + κ₁κ₃ + κ₂κ₃ + a₁² - a₂² - a₃²
 κ₁κ₂κ₃ - κ₁a₁² - κ₂a₂² - κ₃a₃²

In [34]:
sol, st = min_cs_tssos(obj, constraints)

*********************************** TSSOS ***********************************
TSSOS is launching...
-----------------------------------------------------------------------------
The clique sizes of varibles:
[6, 1]
[1, 3]
-----------------------------------------------------------------------------
optimum = 0.00015019388771345474
Global optimality certified with relative optimality gap 0.000010%!
Global optimality certified with relative optimality gap 0.000013%!


(PolyVar{true}[κ₁, κ₂, κ₃, a₁, a₂, a₃, h₁, h₂, h₃] => [-1.1608868148441795e-5, 1.1753383415364485e-7, 3.189335587405016e-7, 1.1886093390429699e-12, 2.8686120743811807e-19, 2.869722101971465e-19, -0.00013618641596120613, 0.00269378242533449, 25.14143860272098], "GLOBAL")

In [39]:
Cˢⁱᵈ = convert.(ComplexF64,subs(Cˢʸᵐᵇ, sol))
Cˢⁱᵈ[1:2,1:2]

2×2 Matrix{ComplexF64}:
 -1.16089e-5+0.0im                 0.0-2.86972e-19im
         0.0+2.86972e-19im  1.17534e-7+0.0im

In [40]:
Cˢⁱᵈ[2:3,2:3]

2×2 Matrix{ComplexF64}:
 1.17534e-7+0.0im                 0.0-1.18861e-12im
        0.0+1.18861e-12im  3.18934e-7+0.0im

In [38]:
Hˢⁱᵈ = convert.(ComplexF64,subs(Hˢʸᵐᵇ, sol))

2×2 Matrix{ComplexF64}:
     12.5707+0.0im         -6.80932e-5+0.00134689im
 -6.80932e-5-0.00134689im     -12.5707+0.0im